config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "events#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  resource :events 
  resource :users
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
    has_many :participations
    has_many :participants, through: :participations, source: :user

  # Validations
  validates :start_date, presence: true
  validate :start_date_cannot_be_in_the_past

  validates :duration, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :duration_must_be_multiple_of_five

  validates :title, presence: true, length: { minimum: 5, maximum: 140 }

  validates :description, presence: true, length: { minimum: 20, maximum: 1000 }

  validates :price, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 1000 }

  validates :location, presence: true

  private

  # Validation method to check that start_date is not in the past
  def start_date_cannot_be_in_the_past
    if start_date.present? && start_date < Time.now
      errors.add(:start_date, "can't be in the past")
    end
  end

  # Validation method to check that duration is a multiple of 5
  def duration_must_be_multiple_of_five
    if duration.present? && duration % 5 != 0
      errors.add(:duration, "must be a multiple of 5")
    end
  end
end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :user
  belongs_to :event
  validates :stripe_customer_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :participations
    has_many :participated_events, through: :participations, source: :event

    after_create :welcome_send

    def welcome_send
      UserMailer.welcome_email(self).deliver_now
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/events/index.html.erb
<h1>Bienvenue sur Eventbrite</h1>

 <P>
 Clique <%= link_to "ici", new_events_path %> pour créer un événement
 </p>

 <h3> Voici les événements à venir : <h3>

 <% @events.each do |event| %>
   
    <h3><%= link_to event.title, events_path(event) %></h3>
    
 <% end %>
         
   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Eventbrite" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  

<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" <%= link_to "Accueil", root_path %> </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" <%= link_to "Créer un événement ", new_events_path %> </a>
        </li>
       
      </ul>
      <span class="navbar-text">
      <% if user_signed_in? %>
      <li>
      <%= button_to "Sign out", destroy_user_session_path, method: :delete %>
      </li>
  
      <li>
        Voici ton email : <%= current_user.email %>
      </li>
  
      
  
      <li>
        <%= link_to "Edit email / password", edit_user_registration_path %>
      </li>
  
    <% else %>
      <li>    
        <%= link_to "Sign in", new_user_session_path %>
      </li>
  
      <li>
        <%= link_to "Sign up", new_user_registration_path %>
      </li>
  
    <% end %>
      </span>
    </div>
  </div>
</nav>
    <%= yield %>
  </body>
</html>

app/views/user/show.html.erb
<h1>User#show</h1>
<p>Find me in app/views/user/show.html.erb</p>